DROP TABLE IF EXISTS "User" CASCADE ;

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS "User" (
  id SERIAL PRIMARY KEY,
  login CITEXT COLLATE "ucs_basic" NOT NULL,
  email CITEXT COLLATE "ucs_basic" UNIQUE NOT NULL,
  password VARCHAR(256) NOT NULL,
  score INTEGER
);
