
CREATE TABLE IF NOT EXISTS "User" (
  id SERIAL PRIMARY KEY,
  login VARCHAR(256) NOT NULL,
  email VARCHAR(256) UNIQUE NOT NULL,
  password VARCHAR(256) NOT NULL,
  score INTEGER,
  rating INTEGER
);